import type { OffStandardEntry, OffStandardReason, OffStandardPresetReason, OffStdEditStatus, ShiftType, ShiftWithUser, User } from '../types';
import { localDateStr } from '../hooks/useFleetBalance';

export interface TripRow {
  depart_time: string;
  arrive_time: string;
  is_shuttle: boolean | null;
  reason: string | null;
}

export function fmtMinutes(totalMinutes: number): string {
  const h = Math.floor(totalMinutes / 60);
  const m = totalMinutes % 60;
  if (h === 0) return `${m}m`;
  return m === 0 ? `${h}h` : `${h}h ${m}m`;
}

export function fmtTime(iso: string): string {
  return new Date(iso).toLocaleTimeString('en-CA', { hour: '2-digit', minute: '2-digit', hour12: false });
}

export function todayDateStr(): string {
  const d = new Date();
  return d.toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' });
}

export function rowToOffStandard(row: Record<string, unknown>): OffStandardEntry {
  return {
    id:              row.id as string,
    startTime:       row.start_time as string,
    stopTime:        row.stop_time as string,
    minutes:         row.minutes as number,
    reason:          row.reason as OffStandardReason,
    explanation:     (row.explanation as string | null) ?? undefined,
    autoFromTrip:    (row.auto_from_trip as boolean) ?? false,
    editedEndTime:   (row.edited_end_time as string | null) ?? undefined,
    editRequestedAt: (row.edit_requested_at as string | null) ?? undefined,
    editRequestedBy: (row.edit_requested_by as string | null) ?? undefined,
    editStatus:      (row.edit_status as OffStdEditStatus | null) ?? null,
    editReviewedBy:  (row.edit_reviewed_by as string | null) ?? undefined,
    editReviewedAt:  (row.edit_reviewed_at as string | null) ?? undefined,
    editStaffNote:       (row.edit_staff_note as string | null) ?? undefined,
    isBackdated:         (row.is_backdated as boolean | null) ?? false,
    backdateApprovedBy:  (row.backdate_approved_by as string | null) ?? undefined,
    backdateApprovedAt:  (row.backdate_approved_at as string | null) ?? undefined,
  };
}

export function shiftTypeLabel(shiftType: ShiftType): string {
  if (shiftType === 'day-off') return 'Day Off';
  if (shiftType === 'pto') return 'PTO';
  if (shiftType === 'sick') return 'Sick Day';
  return `${shiftType.charAt(0).toUpperCase() + shiftType.slice(1)} shift`;
}

export function deriveShiftLine(shifts: ShiftWithUser[], userId: string, date?: string): string {
  const today = date ?? localDateStr(0);
  const todaysShifts = shifts.filter(s => s.userId === userId && s.date === today);
  if (todaysShifts.length === 0) return '8-hour shift';

  const withTimes = todaysShifts.find(s => s.startTime && s.endTime);
  const chosen = withTimes ?? todaysShifts[0];
  if (!chosen) return '8-hour shift';

  const label = shiftTypeLabel(chosen.shiftType);
  if (chosen.startTime && chosen.endTime) {
    return `${label} ${chosen.startTime}-${chosen.endTime}`;
  }
  return label;
}

export function generateOffStandardReport(
  entries: OffStandardEntry[],
  trips: TripRow[],
  user: User,
  shiftLine: string,
  dateLabel?: string,
): string {
  const offTotal = entries.reduce((s, e) => s + e.minutes, 0);

  const lines: string[] = [
    'FLEET GARAGE — OFF-STANDARD TIME REPORT',
    '─'.repeat(37),
    `Name:     ${user.name}`,
    `EEID:     ${user.employeeId}`,
    `Date:     ${dateLabel ?? todayDateStr()}`,
    `Shift:    ${shiftLine}`,
    '',
    'OFF-STANDARD ENTRIES',
    '─'.repeat(37),
  ];

  if (entries.length === 0) {
    lines.push('(none)');
  } else {
    for (const e of entries) {
      const auto = e.autoFromTrip ? '  [auto]' : '';
      const expl = e.explanation ? `  ${e.explanation}` : '';
      lines.push(`${fmtTime(e.startTime)} – ${fmtTime(e.stopTime)}  ${e.reason}${expl}${auto}`);
    }
  }

  lines.push('', `Total off-standard:  ${fmtMinutes(offTotal)}`);

  if (trips.length > 0) {
    lines.push('', 'AIRPORT TRIPS', '─'.repeat(37));
    for (const t of trips) {
      const mins = Math.round(
        (new Date(t.arrive_time).getTime() - new Date(t.depart_time).getTime()) / 60000
      );
      const label = t.is_shuttle ? 'Shuttle Transfer' : (t.reason ?? 'Airport Run');
      lines.push(`${fmtTime(t.depart_time)} – ${fmtTime(t.arrive_time)}  ${label}  (${mins}m)`);
    }
  }

  lines.push(
    '',
    'Manager approval: _________________',
    '─'.repeat(37),
    'Generated by Fleet Garage',
  );

  return lines.join('\n');
}

export function deriveExplanation(
  preset: OffStandardPresetReason | null,
  unit: string,
  freeText: string,
): string {
  if (!preset) return freeText;
  if (preset === 'edv')              return unit ? `Extremely Dirty Vehicle — ${unit}` : 'Extremely Dirty Vehicle';
  if (preset === 'fleeting_cars')    return 'Fleeting cars';
  if (preset === 'closing_duties')   return 'Closing duties';
  if (preset === 'opening_duties')   return 'Opening duties';
  if (preset === 'lot_organization') return 'Lot organization';
  if (preset === 'customer_pickup')  return 'Pickup / drop-off';
  return '';
}
