import { describe, it, expect } from 'vitest';
import {
  fmtMinutes,
  formatDateStr,
  deriveShiftLine,
  buildReport,
  type ReportData,
  type ReportThroughput,
} from '../../src/lib/buildShiftReport';
import type { ShiftWithUser } from '../../src/types';

// ── small helpers ─────────────────────────────────────────────────────────────

describe('fmtMinutes', () => {
  it('formats minutes, whole hours, and mixed', () => {
    expect(fmtMinutes(45)).toBe('45m');
    expect(fmtMinutes(60)).toBe('1h');
    expect(fmtMinutes(125)).toBe('2h 5m');
  });
});

describe('formatDateStr', () => {
  it('builds a long local date from a YYYY-MM-DD string', () => {
    const s = formatDateStr('2026-05-22'); // a Friday
    expect(s).toMatch(/Friday/);
    expect(s).toMatch(/May/);
    expect(s).toMatch(/22/);
    expect(s).toMatch(/2026/);
  });
});

describe('deriveShiftLine', () => {
  function shift(over: Partial<ShiftWithUser>): ShiftWithUser {
    return {
      id: 's1', userId: 'u1', date: '2026-05-22', shiftType: 'closing',
      createdAt: '', updatedAt: '', branchId: 'YWG', user: { name: 'Ana', role: 'VSA' },
      ...over,
    };
  }

  it('defaults when no shift on that day', () => {
    expect(deriveShiftLine([], 'u1', '2026-05-22')).toBe('8-hour shift');
  });

  it('renders label + time range (en-dash)', () => {
    const line = deriveShiftLine([shift({ startTime: '13:30', endTime: '22:00' })], 'u1', '2026-05-22');
    expect(line).toBe('Closing shift 13:30–22:00');
  });

  it('renders label only when no times', () => {
    expect(deriveShiftLine([shift({ shiftType: 'pto' })], 'u1', '2026-05-22')).toBe('PTO');
  });
});

// ── buildReport ───────────────────────────────────────────────────────────────

function baseData(over: Partial<ReportData> = {}): ReportData {
  return {
    shiftLine: 'Closing shift 13:30–22:00',
    dateLabel: 'Friday, May 22, 2026',
    userName: 'Ana Reyes',
    employeeId: 'EMP100',
    shiftType: 'closing',
    offStandard: [],
    trips: [],
    holds: [],
    checkIns: [],
    lostFound: [],
    audits: [],
    issues: [],
    fleetBalance: null,
    throughput: null,
    airportFlipping: false,
    ...over,
  };
}

function throughput(over: Partial<ReportThroughput> = {}): ReportThroughput {
  return {
    shiftType: 'closing',
    openingCleaned: null,
    closingCleaned: null,
    midCleaned: null,
    midShiftHours: null,
    fullDayCleaned: null,
    branchOpHours: 15,
    lotStatus: null,
    baseline: null,
    yourEffort: null,
    actualWindowLabel: null,
    carryOver: 0,
    ...over,
  };
}

describe('buildReport — header & footer', () => {
  it('always includes identity and the footer', () => {
    const r = buildReport(baseData());
    expect(r).toContain('SHIFT REPORT');
    expect(r).toContain('Ana Reyes');
    expect(r).toContain('EMP100');
    expect(r).toContain('Generated by Fleet Garage');
  });
});

describe('buildReport — fleet demand', () => {
  it('shows reservations, returns, and a supply-gap warning when demand exceeds returns', () => {
    const r = buildReport(baseData({ fleetBalance: { outCount: 50, inCount: 40, isProjected: false } }));
    expect(r).toContain('FLEET DEMAND');
    expect(r).toContain('Reservations: 50');
    expect(r).toContain('Returns:      40');
    expect(r).toContain('Supply gap: -10');
  });

  it('marks projected balances as estimated and shows positive deltas', () => {
    const r = buildReport(baseData({
      fleetBalance: { outCount: 40, inCount: 50, isProjected: true },
      throughput: throughput({ fullDayCleaned: 45 }),
    }));
    expect(r).toContain('FLEET DEMAND  (Est.)');
    expect(r).toContain('(+5 above demand)');   // 45 cleaned > 40 demand
    expect(r).toContain('(+10 more came back)'); // 50 in - 40 out
  });
});

describe('buildReport — throughput', () => {
  it('closing shift lists opening, closing, full-day and rates', () => {
    const r = buildReport(baseData({
      fleetBalance: { outCount: 40, inCount: 40, isProjected: false },
      throughput: throughput({ openingCleaned: 30, closingCleaned: 20, fullDayCleaned: 50, branchOpHours: 10 }),
    }));
    expect(r).toContain('Opening crew: 30 cars');
    expect(r).toContain('Closing crew: 20 cars');
    expect(r).toContain('Full day: 50 of 40 needed');
    expect(r).toContain('Branch rate: 5.0/hr');  // 50 / 10
    expect(r).toContain('Shift rate: 2.5/hr');    // 20 / 8
  });

  it('opening shift only reports the opening line', () => {
    const r = buildReport(baseData({
      shiftType: 'opening',
      throughput: throughput({ shiftType: 'opening', openingCleaned: 30 }),
    }));
    expect(r).toContain('Opening crew: 30 cars');
    expect(r).not.toContain('Closing crew');
  });

  it('surfaces the airport-flip flag in the throughput block when active', () => {
    const r = buildReport(baseData({
      throughput: throughput({ closingCleaned: 20, fullDayCleaned: 40, branchOpHours: 8 }),
      airportFlipping: true,
    }));
    expect(r).toContain('✈️ Airport flipping active');
  });

  it('omits the airport-flip flag when no airport-flip time was logged', () => {
    const r = buildReport(baseData({
      throughput: throughput({ closingCleaned: 20, fullDayCleaned: 40, branchOpHours: 8 }),
      airportFlipping: false,
    }));
    expect(r).not.toContain('Airport flipping');
  });

  it('shows the standard window range when no actual hours are logged', () => {
    const r = buildReport(baseData({
      shiftType: 'opening',
      throughput: throughput({ shiftType: 'opening', openingCleaned: 30 }),
    }));
    expect(r).toContain('Opening crew: 30 cars (06:45–15:15)');
  });

  it('shows the actual worked window on the viewer line when logged, keeping reference crews standard', () => {
    const r = buildReport(baseData({
      shiftType: 'opening',
      throughput: throughput({ shiftType: 'opening', openingCleaned: 30, actualWindowLabel: '06:45–17:00' }),
    }));
    expect(r).toContain('Opening crew: 30 cars (06:45–17:00)');

    // Closing viewer's own line uses the actual window; the opening-crew reference line stays standard.
    const closing = buildReport(baseData({
      shiftType: 'closing',
      throughput: throughput({ shiftType: 'closing', openingCleaned: 30, closingCleaned: 24, actualWindowLabel: '11:00–22:00' }),
    }));
    expect(closing).toContain('Closing crew: 24 cars (11:00–22:00)');
    expect(closing).toContain('Opening crew: 30 cars (06:45–15:15)');
  });

  it('prompts to log OTH when there is none, and renders the precomputed personal rate when there is', () => {
    const noOth = buildReport(baseData({
      throughput: throughput({ shiftType: 'closing', closingCleaned: 16, yourEffort: 2.0 }),
    }));
    // No off-standard logged → encouragement message, not the rate.
    expect(noOth).toContain('Log off-standard time to see your personal rate');

    // yourEffort is computed upstream via computeShiftRates (16 / (8h − 2h) = 2.7);
    // buildReport just renders it once off-standard exists.
    const withOth = buildReport(baseData({
      offStandard: [{ startTime: '', stopTime: '', minutes: 120, reason: 'OTH', explanation: null, autoFromTrip: false }],
      throughput: throughput({ shiftType: 'closing', closingCleaned: 16, yourEffort: 16 / 6 }),
    }));
    expect(withOth).toContain('Personal: 2.7/hr');
  });
});

describe('buildReport — off-standard summary', () => {
  it('shows (none) with no entries', () => {
    expect(buildReport(baseData())).toContain('(none)');
  });

  it('breaks down manual OTH / WFW / auto and counts trips + interruptions', () => {
    const r = buildReport(baseData({
      offStandard: [
        { startTime: '', stopTime: '', minutes: 30, reason: 'OTH', explanation: null, autoFromTrip: false },
        { startTime: '', stopTime: '', minutes: 15, reason: 'WFW', explanation: null, autoFromTrip: false },
        { startTime: '', stopTime: '', minutes: 10, reason: 'OTH', explanation: null, autoFromTrip: true },
      ],
      trips: [
        { departTime: '2026-05-22T14:00:00Z', arriveTime: '2026-05-22T14:20:00Z', isShuffle: null, reason: null, isVsaInterruption: true, queueAtDeparture: null },
      ],
    }));
    expect(r).toContain('Total: 55m');
    expect(r).toContain('Manual OTH · 30m');
    expect(r).toContain('WFW · 15m');
    expect(r).toContain('Auto-logged · 10m');
    expect(r).toContain('Interruptions: 1');
  });
});

describe('buildReport — washbay queue warning', () => {
  it('warns when a trip departed with a 10+ queue', () => {
    const r = buildReport(baseData({
      trips: [
        { departTime: '2026-05-22T14:00:00Z', arriveTime: '2026-05-22T14:20:00Z', isShuffle: null, reason: null, isVsaInterruption: false, queueAtDeparture: 'TOO_MUCH' },
      ],
    }));
    expect(r).toContain('WASHBAY QUEUE AT DEPARTURE');
    expect(r).toContain('Queue: 10+');
    expect(r).toContain('departed with washbay queue at 10+');
  });
});

describe('buildReport — conditional sections', () => {
  it('omits optional sections when their lists are empty', () => {
    const r = buildReport(baseData());
    for (const section of ['UNITS FLAGGED', 'VEHICLES CHECKED IN', 'LOST & FOUND', 'AUDITS', 'ISSUES REPORTED']) {
      expect(r).not.toContain(section);
    }
  });

  it('renders sections when their lists have entries', () => {
    const r = buildReport(baseData({
      holds: [{ flaggedAt: '2026-05-22T14:00:00Z', holdTypes: ['mechanical', 'damage'], vehicleUnit: 'U1', vehiclePlate: 'ABC', description: 'dent' }],
      issues: [{ reportedAt: '2026-05-22T14:00:00Z', title: 'Bay light out', severity: 'high' }],
    }));
    expect(r).toContain('UNITS FLAGGED');
    expect(r).toContain('Mechanical & Damage hold');
    expect(r).toContain('ISSUES REPORTED');
    expect(r).toContain('[High] Bay light out');
  });
});
