import { useState, useEffect } from 'react';
import { hapticLight, hapticMedium } from '../lib/haptics';
import { useGarage } from '../context/GarageContext';
import type { OffStandardEntry, OffStandardReason, OffStandardPresetReason, User } from '../types';
import { OFF_STANDARD_LABELS } from '../types';
import { localDateStr } from '../hooks/useFleetBalance';
import { USERS } from '../data/mock';

const SHIFT_HOURS = 8;
const MIN_ENTRY_MINUTES = 5;
const STANDARD_RATE = 3.0;

const REASONS: OffStandardReason[] = ['CLASS', 'WFW', 'MTG', 'WTH', 'OTH'];

interface Props {
  entries: OffStandardEntry[];
  onAddEntry: (entry: OffStandardEntry) => void;
  saveError?: boolean;
  user: User;
}

function fmtMinutes(totalMinutes: number): string {
  const h = Math.floor(totalMinutes / 60);
  const m = totalMinutes % 60;
  if (h === 0) return `${m}m`;
  return m === 0 ? `${h}h` : `${h}h ${m}m`;
}

function fmtTime(iso: string): string {
  return new Date(iso).toLocaleTimeString('en-CA', { hour: '2-digit', minute: '2-digit', hour12: false });
}

function todayDateStr(): string {
  const d = new Date();
  return d.toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' });
}

function generateReportText(entries: OffStandardEntry[], user: User, carsCleaned: number): string {
  const offTotal = entries.reduce((s, e) => s + e.minutes, 0);
  const activeMinutes = Math.max(0, SHIFT_HOURS * 60 - offTotal);
  const activeHours = activeMinutes / 60;
  const rate = activeHours > 0 ? carsCleaned / activeHours : 0;

  const lines: string[] = [
    'OFF-STANDARD TIME REPORT',
    '─'.repeat(37),
    `Name:     ${user.name}`,
    `EEID:     ${user.employeeId}`,
    `Date:     ${todayDateStr()}`,
    `Shift:    8-hour shift`,
    '',
    'OFF-STANDARD ENTRIES',
    '─'.repeat(37),
  ];

  if (entries.length === 0) {
    lines.push('(none)');
  } else {
    for (const e of entries) {
      const auto = e.autoFromTrip ? '  [auto]' : '';
      const expl = e.explanation ? `  ${e.explanation}` : '';
      lines.push(`${fmtTime(e.startTime)} – ${fmtTime(e.stopTime)}  ${e.reason}${expl}${auto}`);
    }
  }

  const rateLabel = rate >= STANDARD_RATE ? '✅ Above standard' : rate >= 2.5 ? '⚠️ Near standard' : '❌ Below standard';

  lines.push(
    '',
    '─'.repeat(37),
    `Total off-standard:  ${fmtMinutes(offTotal)}`,
    `Active cleaning:     ${fmtMinutes(activeMinutes)}`,
    `Cars cleaned (team): ${carsCleaned}`,
    `Adjusted team rate:  ${rate.toFixed(1)} / hr  ${rateLabel}`,
    '',
    'Manager approval: _________________',
    '─'.repeat(37),
    'Generated by Fleet Garage',
  );

  return lines.join('\n');
}

// ── Timer section ─────────────────────────────────────────────────────────────

type TimerState = 'idle' | 'running' | 'pending-confirm';

function ElapsedTicker({ startTime }: { startTime: string }) {
  const [elapsed, setElapsed] = useState(0);
  useEffect(() => {
    const tick = () => setElapsed(Math.floor((Date.now() - new Date(startTime).getTime()) / 1000));
    tick();
    const id = setInterval(tick, 1000);
    return () => clearInterval(id);
  }, [startTime]);
  const m = Math.floor(elapsed / 60);
  const s = elapsed % 60;
  return <span className="font-mono tabular-nums">{m}:{String(s).padStart(2, '0')}</span>;
}

// ── Main component ────────────────────────────────────────────────────────────

export function OffStandardTimeLog({ entries, onAddEntry, saveError, user }: Props) {
  const { getTodayWashbayLog, holds, vehicles } = useGarage();
  const washbayLog = getTodayWashbayLog();
  const carsNum = washbayLog
    ? Math.max(0, (washbayLog.fullPages * 19 + washbayLog.lastPageEntries) - washbayLog.carsRemaining)
    : 0;

  const [timerState, setTimerState]         = useState<TimerState>('idle');
  const [selectedReason, setSelectedReason] = useState<OffStandardReason>('WFW');
  const [startTimestamp, setStartTimestamp] = useState<string>('');
  const [stopTimestamp, setStopTimestamp]   = useState<string>('');
  const [pendingMinutes, setPendingMinutes] = useState(0);
  const [explanation, setExplanation]       = useState('');
  const [copied, setCopied]                 = useState(false);

  // Preset + EDV state
  const [selectedPreset, setSelectedPreset]     = useState<OffStandardPresetReason | null>(null);
  const [edvLinkedHoldId, setEdvLinkedHoldId]   = useState<string | null>(null);
  const [edvUnitNumber, setEdvUnitNumber]       = useState<string>('');
  const [edvManagerName, setEdvManagerName]     = useState<string>('');
  const [edvNoMatch, setEdvNoMatch]             = useState(false);

  // ── Preset helpers ────────────────────────────────────────────────────────

  function selectPreset(preset: OffStandardPresetReason) {
    hapticLight();
    const next = selectedPreset === preset ? null : preset;
    setSelectedPreset(next);
    setEdvLinkedHoldId(null);
    setEdvUnitNumber('');
    setEdvManagerName('');
    setEdvNoMatch(false);

    if (next !== 'edv') return;

    const today = localDateStr(0);
    const edvHold = holds.find(h =>
      h.holdTypes.includes('detail') &&
      h.status === 'RELEASED' &&
      h.release?.approvedAt.startsWith(today) &&
      !h.offstandardLinked
    );

    if (!edvHold) { setEdvNoMatch(true); return; }

    const vehicle = vehicles.find(v => v.id === edvHold.vehicleId);
    const manager = USERS.find(u => u.id === edvHold.release?.approvedById);

    setEdvLinkedHoldId(edvHold.id);
    setEdvUnitNumber(vehicle?.unitNumber ?? edvHold.vehicleId);
    setEdvManagerName(manager?.name ?? edvHold.release?.approvedById ?? 'Unknown');
  }

  function presetExplanation(): string {
    if (selectedPreset === 'edv')           return `EDV — ${edvUnitNumber} — Released by ${edvManagerName}`;
    if (selectedPreset === 'fleeting_cars') return 'Fleeting cars';
    if (selectedPreset === 'closing_duties') return 'Closing duties';
    return '';
  }

  // ── Timer controls ────────────────────────────────────────────────────────

  const handleStart = () => {
    hapticLight();
    const now = new Date().toISOString();
    setStartTimestamp(now);
    if (selectedPreset) setExplanation(presetExplanation());
    setTimerState('running');
  };

  const handleStop = () => {
    hapticLight();
    const now = new Date().toISOString();
    setStopTimestamp(now);
    const mins = Math.round((new Date(now).getTime() - new Date(startTimestamp).getTime()) / 60000);
    setPendingMinutes(mins);
    setTimerState('pending-confirm');
  };

  const handleConfirm = () => {
    if (pendingMinutes < MIN_ENTRY_MINUTES) {
      handleDiscard();
      return;
    }
    hapticLight();
    onAddEntry({
      id:            `manual-${Date.now()}`,
      startTime:     startTimestamp,
      stopTime:      stopTimestamp,
      minutes:       pendingMinutes,
      reason:        selectedReason,
      explanation:   explanation.trim() || undefined,
      autoFromTrip:  false,
      presetReason:  selectedPreset,
      linkedHoldId:  selectedPreset === 'edv' ? edvLinkedHoldId : null,
    });
    setTimerState('idle');
    setExplanation('');
    setPendingMinutes(0);
    setSelectedPreset(null);
    setEdvLinkedHoldId(null);
    setEdvUnitNumber('');
    setEdvManagerName('');
    setEdvNoMatch(false);
  };

  const handleDiscard = () => {
    setTimerState('idle');
    setExplanation('');
    setPendingMinutes(0);
    setStartTimestamp('');
    setStopTimestamp('');
    setSelectedPreset(null);
    setEdvLinkedHoldId(null);
    setEdvUnitNumber('');
    setEdvManagerName('');
    setEdvNoMatch(false);
  };

  // ── Save error banner ─────────────────────────────────────────────────────

  const saveErrorBanner = saveError ? (
    <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/40 rounded-lg px-4 py-3">
      <p className="text-xs font-semibold text-red-700 dark:text-red-400">Couldn't save — check connection and try again.</p>
    </div>
  ) : null;

  // ── Tally ─────────────────────────────────────────────────────────────────

  const offTotal      = entries.reduce((s, e) => s + e.minutes, 0);
  const activeMinutes = Math.max(0, SHIFT_HOURS * 60 - offTotal);
  const activeHours   = activeMinutes / 60;
  const rate          = activeHours > 0 && carsNum > 0 ? carsNum / activeHours : 0;
  const rateColor     = !washbayLog ? 'text-gray-400 dark:text-gray-500'
    : rate >= STANDARD_RATE ? 'text-green-600 dark:text-green-400'
    : rate >= 2.5 ? 'text-amber-500'
    : 'text-red-600 dark:text-red-400';

  // ── Export ────────────────────────────────────────────────────────────────

  const handleExport = async () => {
    hapticMedium();
    // Sync cars value from DOM (carsRef) into the generator
    const reportText = generateReportText(entries, user, carsNum);
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Off-Standard Report — ${user.name} · ${todayDateStr()}`,
          text: reportText,
        });
        return;
      } catch {
        // fall through to clipboard
      }
    }
    await navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  // ── Render ────────────────────────────────────────────────────────────────

  const INPUT = 'w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-700 text-sm text-gray-900 dark:text-gray-100 bg-white dark:bg-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition';

  return (
    <div className="space-y-5">

      {/* Timer card */}
      <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden transition-colors">
        <div className="px-4 py-3 border-b border-gray-100 dark:border-gray-800">
          <p className="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-widest">Log Off-Standard Time</p>
        </div>
        <div className="p-4 space-y-4">

          {/* Reason pills — always visible */}
          <div>
            <p className="text-xs text-gray-400 dark:text-gray-500 mb-2">Reason</p>
            <div className="flex flex-wrap gap-2">
              {REASONS.map(r => (
                <button
                  key={r}
                  type="button"
                  disabled={timerState === 'running'}
                  onClick={() => { if (timerState !== 'running') { hapticLight(); setSelectedReason(r); } }}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition cursor-pointer disabled:cursor-default ${
                    selectedReason === r
                      ? 'bg-yellow-400 border-yellow-400 text-gray-900'
                      : 'border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400 hover:border-gray-300 dark:hover:border-gray-600'
                  }`}
                >
                  {r} · {OFF_STANDARD_LABELS[r].full}
                </button>
              ))}
            </div>
          </div>

          {/* Preset selector — visible when OTH selected and timer not running */}
          {selectedReason === 'OTH' && timerState === 'idle' && (
            <div>
              <p className="text-xs text-gray-400 dark:text-gray-500 mb-2">Quick reason (optional)</p>
              <div className="flex flex-wrap gap-2">
                {([
                  { value: 'fleeting_cars',  label: 'Fleeting Cars' },
                  { value: 'closing_duties', label: 'Closing Duties' },
                  { value: 'edv',            label: 'EDV' },
                ] as { value: OffStandardPresetReason; label: string }[]).map(p => (
                  <button
                    key={p.value}
                    type="button"
                    onClick={() => selectPreset(p.value)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition cursor-pointer ${
                      selectedPreset === p.value
                        ? 'bg-yellow-400 border-yellow-400 text-gray-900'
                        : 'border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400 hover:border-gray-300 dark:hover:border-gray-600'
                    }`}
                  >
                    {p.label}
                  </button>
                ))}
              </div>

              {/* EDV auto-populate result */}
              {selectedPreset === 'edv' && !edvNoMatch && edvLinkedHoldId && (
                <div className="mt-2 px-3 py-2 rounded-lg bg-teal-50 dark:bg-teal-900/20 border border-teal-200 dark:border-teal-800/40 text-xs space-y-0.5">
                  <p className="font-semibold text-teal-800 dark:text-teal-300">Hold matched</p>
                  <p className="text-teal-700 dark:text-teal-400">Unit: <span className="font-medium">{edvUnitNumber}</span></p>
                  <p className="text-teal-700 dark:text-teal-400">Released by: <span className="font-medium">{edvManagerName}</span></p>
                  <p className="text-teal-600 dark:text-teal-500 mt-1">💡 Typical EDV clean: 30–40 min</p>
                </div>
              )}

              {/* EDV no-match warning */}
              {selectedPreset === 'edv' && edvNoMatch && (
                <div className="mt-2 px-3 py-2 rounded-lg bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/40 text-xs text-amber-700 dark:text-amber-400">
                  No released detail hold found for today. Log manually or check Holds for the unit.
                </div>
              )}
            </div>
          )}

          <p className="text-xs text-blue-600 dark:text-blue-400">
            🔗 Airport trips log automatically from the Movement Log — no need to add them here.
          </p>

          {/* Timer idle → Start */}
          {timerState === 'idle' && (
            <button
              type="button"
              onClick={handleStart}
              className="w-full py-3 rounded-xl bg-yellow-400 hover:bg-yellow-500 text-gray-900 text-sm font-semibold transition cursor-pointer"
            >
              Start
            </button>
          )}

          {/* Timer running → elapsed + Stop */}
          {timerState === 'running' && (
            <div className="space-y-3">
              <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/40 rounded-xl px-4 py-4 text-center">
                <p className="text-xs font-semibold text-amber-700 dark:text-amber-400 uppercase tracking-widest mb-1">
                  {selectedReason} · {OFF_STANDARD_LABELS[selectedReason].full}
                </p>
                <p className="text-3xl font-bold text-amber-600 dark:text-amber-400">
                  <ElapsedTicker startTime={startTimestamp} />
                </p>
                <p className="text-xs text-amber-600/70 dark:text-amber-500/70 mt-1">
                  Started {fmtTime(startTimestamp)}
                </p>
              </div>
              <button
                type="button"
                onClick={handleStop}
                className="w-full py-3 rounded-xl bg-gray-900 dark:bg-gray-100 hover:bg-gray-800 dark:hover:bg-white text-white dark:text-gray-900 text-sm font-semibold transition cursor-pointer"
              >
                Stop
              </button>
            </div>
          )}

          {/* Pending confirm — show duration, explanation, confirm/discard */}
          {timerState === 'pending-confirm' && (
            <div className="space-y-3">
              <div className={`rounded-xl px-4 py-3 border ${
                pendingMinutes < MIN_ENTRY_MINUTES
                  ? 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800/40'
                  : 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800/40'
              }`}>
                <p className={`text-sm font-semibold ${pendingMinutes < MIN_ENTRY_MINUTES ? 'text-red-700 dark:text-red-400' : 'text-green-700 dark:text-green-400'}`}>
                  {fmtTime(startTimestamp)} – {fmtTime(stopTimestamp)} · {fmtMinutes(pendingMinutes)}
                </p>
                {pendingMinutes < MIN_ENTRY_MINUTES && (
                  <p className="text-xs text-red-600 dark:text-red-500 mt-0.5">Under 5 minutes — will be discarded</p>
                )}
              </div>

              {pendingMinutes >= MIN_ENTRY_MINUTES && (
                <div>
                  <label className="text-xs text-gray-400 dark:text-gray-500 mb-1 block">Explanation (optional)</label>
                  <input
                    type="text"
                    value={explanation}
                    onChange={e => setExplanation(e.target.value)}
                    placeholder="e.g. Waiting for dirties to arrive…"
                    className={INPUT}
                    autoFocus
                  />
                </div>
              )}

              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={handleConfirm}
                  className={`flex-1 py-3 rounded-xl text-sm font-semibold transition cursor-pointer ${
                    pendingMinutes >= MIN_ENTRY_MINUTES
                      ? 'bg-yellow-400 hover:bg-yellow-500 text-gray-900'
                      : 'bg-gray-100 dark:bg-gray-800 text-gray-400 cursor-not-allowed'
                  }`}
                >
                  {pendingMinutes >= MIN_ENTRY_MINUTES ? 'Add Entry' : 'Discard'}
                </button>
                <button
                  type="button"
                  onClick={handleDiscard}
                  className="px-4 py-3 rounded-xl text-sm font-semibold text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 transition cursor-pointer"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
          {saveErrorBanner}
        </div>
      </div>

      {/* Entry list */}
      {entries.length > 0 && (
        <div className="space-y-2">
          <p className="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-widest">Entries</p>
          {entries.map(entry => (
            <div
              key={entry.id}
              className={`rounded-xl border px-4 py-3 transition-colors ${
                entry.autoFromTrip
                  ? 'bg-blue-50 dark:bg-blue-900/10 border-blue-200 dark:border-blue-800/40'
                  : 'bg-white dark:bg-gray-900 border-gray-200 dark:border-gray-800'
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-xs font-semibold text-gray-900 dark:text-gray-100">
                      {fmtTime(entry.startTime)} – {fmtTime(entry.stopTime)}
                    </span>
                    <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400">
                      {entry.reason}
                    </span>
                    <span className="text-xs text-gray-500 dark:text-gray-400">
                      {fmtMinutes(entry.minutes)}
                    </span>
                    {entry.autoFromTrip && (
                      <span className="text-[10px] text-blue-600 dark:text-blue-400 font-medium">🔗 From movement log</span>
                    )}
                  </div>
                  {entry.explanation && (
                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">{entry.explanation}</p>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Shift summary + export */}
      <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden transition-colors">
        <div className="px-4 py-3 border-b border-gray-100 dark:border-gray-800">
          <p className="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-widest">Shift Summary</p>
        </div>
        <div className="p-4 space-y-4">
          <div className="space-y-2 text-sm">
            <div className="flex justify-between text-gray-600 dark:text-gray-400">
              <span>Shift hours</span>
              <span className="font-medium text-gray-900 dark:text-gray-100">{SHIFT_HOURS}h</span>
            </div>
            <div className="flex justify-between text-gray-600 dark:text-gray-400">
              <span>Off-standard total</span>
              <span className="font-medium text-gray-900 dark:text-gray-100">{fmtMinutes(offTotal)}</span>
            </div>
            <div className="flex justify-between text-gray-600 dark:text-gray-400 pt-1 border-t border-gray-100 dark:border-gray-800">
              <span>Active cleaning</span>
              <span className="font-semibold text-gray-900 dark:text-gray-100">{fmtMinutes(activeMinutes)}</span>
            </div>
          </div>

          <div className="flex justify-between text-sm text-gray-600 dark:text-gray-400">
            <span>Cars cleaned (team)</span>
            {washbayLog ? (
              <span className="font-semibold text-gray-900 dark:text-gray-100">{carsNum}</span>
            ) : (
              <span className="text-xs text-gray-400 dark:text-gray-500 italic">Submit closing duties to see</span>
            )}
          </div>

          {washbayLog && (
            <div className={`rounded-lg px-4 py-3 border ${
              rate >= STANDARD_RATE
                ? 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800/50'
                : rate >= 2.5
                ? 'bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800/50'
                : 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800/50'
            }`}>
              <div className="flex justify-between items-baseline">
                <span className="text-xs text-gray-500 dark:text-gray-400">Standard rate</span>
                <span className="text-sm font-medium text-gray-600 dark:text-gray-400">{STANDARD_RATE.toFixed(1)} / hr</span>
              </div>
              <div className="flex justify-between items-baseline mt-1">
                <span className="text-xs text-gray-500 dark:text-gray-400">Team rate</span>
                <span className={`text-lg font-bold ${rateColor}`}>{rate.toFixed(1)} / hr</span>
              </div>
            </div>
          )}

          <button
            type="button"
            onClick={handleExport}
            className="w-full py-3 rounded-xl bg-gray-900 dark:bg-gray-100 hover:bg-gray-800 dark:hover:bg-white text-white dark:text-gray-900 text-sm font-semibold transition cursor-pointer"
          >
            {copied ? '✓ Copied to clipboard' : 'Export Shift Report'}
          </button>
        </div>
      </div>

    </div>
  );
}
