import { useState, useEffect } from 'react';
import { hapticLight, hapticMedium } from '../lib/haptics';
import { useGarage } from '../context/GarageContext';
import { useSchedule } from '../context/ScheduleContext';
import { supabase } from '../lib/supabase';
import type { OffStandardEntry, OffStandardReason, OffStandardPresetReason, User } from '../types';
import { OFF_STANDARD_LABELS } from '../types';
import { localDateStr } from '../hooks/useFleetBalance';
import { USERS } from '../data/mock';

const SHIFT_HOURS = 8;
const MIN_ENTRY_MINUTES = 5;
const STANDARD_RATE = 3.0;

const REASONS: OffStandardReason[] = ['CLASS', 'WFW', 'MTG', 'WTH', 'OTH'];

interface Props {
  user: User;
  refreshTrigger?: number;
}

function fmtMinutes(totalMinutes: number): string {
  const h = Math.floor(totalMinutes / 60);
  const m = totalMinutes % 60;
  if (h === 0) return `${m}m`;
  return m === 0 ? `${h}h` : `${h}h ${m}m`;
}

function fmtTime(iso: string): string {
  return new Date(iso).toLocaleTimeString('en-CA', { hour: '2-digit', minute: '2-digit', hour12: false });
}

function todayDateStr(): string {
  const d = new Date();
  return d.toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' });
}

function rowToOffStandard(row: Record<string, unknown>): OffStandardEntry {
  return {
    id:           row.id as string,
    startTime:    row.start_time as string,
    stopTime:     row.stop_time as string,
    minutes:      row.minutes as number,
    reason:       row.reason as OffStandardReason,
    explanation:  (row.explanation as string | null) ?? undefined,
    autoFromTrip: (row.auto_from_trip as boolean) ?? false,
  };
}

function generateReportText(entries: OffStandardEntry[], user: User, carsCleaned: number): string {
  const offTotal = entries.reduce((s, e) => s + e.minutes, 0);
  const activeMinutes = Math.max(0, SHIFT_HOURS * 60 - offTotal);
  const activeHours = activeMinutes / 60;
  const rate = activeHours > 0 ? carsCleaned / activeHours : 0;

  const lines: string[] = [
    'OFF-STANDARD TIME REPORT',
    '─'.repeat(37),
    `Name:     ${user.name}`,
    `EEID:     ${user.employeeId}`,
    `Date:     ${todayDateStr()}`,
    `Shift:    8-hour shift`,
    '',
    'OFF-STANDARD ENTRIES',
    '─'.repeat(37),
  ];

  if (entries.length === 0) {
    lines.push('(none)');
  } else {
    for (const e of entries) {
      const auto = e.autoFromTrip ? '  [auto]' : '';
      const expl = e.explanation ? `  ${e.explanation}` : '';
      lines.push(`${fmtTime(e.startTime)} – ${fmtTime(e.stopTime)}  ${e.reason}${expl}${auto}`);
    }
  }

  const rateLabel = rate >= STANDARD_RATE ? '✅ Above standard' : rate >= 2.5 ? '⚠️ Near standard' : '❌ Below standard';

  lines.push(
    '',
    '─'.repeat(37),
    `Total off-standard:  ${fmtMinutes(offTotal)}`,
    `Active cleaning:     ${fmtMinutes(activeMinutes)}`,
    `Cars cleaned (team): ${carsCleaned}`,
    `Adjusted team rate:  ${rate.toFixed(1)} / hr  ${rateLabel}`,
    '',
    'Manager approval: _________________',
    '─'.repeat(37),
    'Generated by Fleet Garage',
  );

  return lines.join('\n');
}

// ── Timer section ─────────────────────────────────────────────────────────────

type TimerState = 'idle' | 'running' | 'complete';

function ElapsedTicker({ startTime }: { startTime: string }) {
  const [elapsed, setElapsed] = useState(0);
  useEffect(() => {
    const tick = () => setElapsed(Math.floor((Date.now() - new Date(startTime).getTime()) / 1000));
    tick();
    const id = setInterval(tick, 1000);
    return () => clearInterval(id);
  }, [startTime]);
  const m = Math.floor(elapsed / 60);
  const s = elapsed % 60;
  return <span className="font-mono tabular-nums">{m}:{String(s).padStart(2, '0')}</span>;
}

// ── Main component ────────────────────────────────────────────────────────────

export function OffStandardTimeLog({ user, refreshTrigger }: Props) {
  const { getTodayWashbayLog, holds, vehicles } = useGarage();
  const { isPeakSeason } = useSchedule();
  const washbayLog = getTodayWashbayLog();
  const carsNum = washbayLog
    ? Math.max(0, (washbayLog.fullPages * 19 + washbayLog.lastPageEntries) - washbayLog.carsRemaining)
    : 0;

  const [timerState, setTimerState]         = useState<TimerState>('idle');
  const [inProgressId, setInProgressId]     = useState<string | null>(null);
  const [selectedReason, setSelectedReason] = useState<OffStandardReason>('WFW');
  const [startTimestamp, setStartTimestamp] = useState<string>('');
  const [stopTimestamp, setStopTimestamp]   = useState<string>('');
  const [pendingMinutes, setPendingMinutes] = useState(0);
  const [explanation, setExplanation]       = useState('');
  const [copied, setCopied]                 = useState(false);
  const [startError, setStartError]         = useState(false);
  const [entries, setEntries]               = useState<OffStandardEntry[]>([]);

  // Preset + EDV state
  const [selectedPreset, setSelectedPreset]     = useState<OffStandardPresetReason | null>(null);
  const [edvLinkedHoldId, setEdvLinkedHoldId]   = useState<string | null>(null);
  const [edvUnitNumber, setEdvUnitNumber]       = useState<string>('');
  const [edvManagerName, setEdvManagerName]     = useState<string>('');
  const [edvNoMatch, setEdvNoMatch]             = useState(false);

  // Load completed entries for today
  useEffect(() => {
    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);
    supabase
      .from('off_standard_entries')
      .select('*')
      .eq('user_id', user.id)
      .eq('status', 'complete')
      .gte('start_time', todayStart.toISOString())
      .order('start_time', { ascending: true })
      .then(({ data }) => {
        if (data) setEntries((data as Record<string, unknown>[]).map(rowToOffStandard));
      });
  }, [user.id, refreshTrigger]);

  // Recovery: restore any in_progress entry on mount
  useEffect(() => {
    supabase
      .from('off_standard_entries')
      .select('*')
      .eq('user_id', user.id)
      .eq('status', 'in_progress')
      .maybeSingle()
      .then(({ data }) => {
        if (!data) return;
        const row = data as Record<string, unknown>;
        setInProgressId(row.id as string);
        setStartTimestamp(row.start_time as string);
        setSelectedReason(row.reason as OffStandardReason);
        setExplanation((row.explanation as string | null) ?? '');
        if (row.preset_reason) setSelectedPreset(row.preset_reason as OffStandardPresetReason);
        setTimerState('running');
      });
  }, [user.id]);

  // ── Preset helpers ────────────────────────────────────────────────────────

  function selectPreset(preset: OffStandardPresetReason) {
    hapticLight();
    const next = selectedPreset === preset ? null : preset;
    setSelectedPreset(next);
    setEdvLinkedHoldId(null);
    setEdvUnitNumber('');
    setEdvManagerName('');
    setEdvNoMatch(false);

    if (next !== 'edv') return;

    const today = localDateStr(0);
    const edvHold = holds.find(h =>
      h.holdTypes.includes('detail') &&
      h.status === 'RELEASED' &&
      h.release?.approvedAt.startsWith(today) &&
      !h.offstandardLinked
    );

    if (!edvHold) { setEdvNoMatch(true); return; }

    const vehicle = vehicles.find(v => v.id === edvHold.vehicleId);
    const manager = USERS.find(u => u.id === edvHold.release?.approvedById);

    setEdvLinkedHoldId(edvHold.id);
    setEdvUnitNumber(vehicle?.unitNumber ?? edvHold.vehicleId);
    setEdvManagerName(manager?.name ?? edvHold.release?.approvedById ?? 'Unknown');
  }

  function presetExplanation(): string {
    if (selectedPreset === 'edv')            return `EDV — ${edvUnitNumber} — Released by ${edvManagerName}`;
    if (selectedPreset === 'fleeting_cars')  return 'Fleeting cars';
    if (selectedPreset === 'closing_duties') return 'Closing duties';
    return '';
  }

  // ── DB helpers ────────────────────────────────────────────────────────────

  const saveNotes = async (val: string) => {
    if (!inProgressId) return;
    await supabase
      .from('off_standard_entries')
      .update({ explanation: val.trim() || null })
      .eq('id', inProgressId);
  };

  // ── Timer controls ────────────────────────────────────────────────────────

  const handleStart = async () => {
    hapticLight();
    setStartError(false);
    const now = new Date().toISOString();
    const expl = selectedPreset ? presetExplanation() : explanation;
    if (selectedPreset) setExplanation(expl);

    const { data, error } = await supabase
      .from('off_standard_entries')
      .insert({
        user_id:        user.id,
        branch_id:      user.branchId,
        date:           localDateStr(0),
        start_time:     now,
        stop_time:      null,
        minutes:        null,
        reason:         selectedReason,
        explanation:    expl.trim() || null,
        auto_from_trip: false,
        status:         'in_progress',
        ...(selectedPreset ? { preset_reason: selectedPreset } : {}),
        ...(selectedPreset === 'edv' && edvLinkedHoldId ? { linked_hold_id: edvLinkedHoldId } : {}),
      })
      .select('id')
      .single();

    if (error) {
      console.error('Off-standard start write failed:', error);
      setStartError(true);
      return;
    }

    setInProgressId((data as { id: string }).id);
    setStartTimestamp(now);
    setTimerState('running');
  };

  const handleEnd = async () => {
    hapticLight();
    const now = new Date().toISOString();
    const mins = Math.round(
      (new Date(now).getTime() - new Date(startTimestamp).getTime()) / 60000
    );

    if (mins < MIN_ENTRY_MINUTES) {
      if (inProgressId) {
        await supabase.from('off_standard_entries').delete().eq('id', inProgressId);
      }
      handleDiscard();
      return;
    }

    const { error } = await supabase
      .from('off_standard_entries')
      .update({
        stop_time:   now,
        minutes:     mins,
        explanation: explanation.trim() || null,
        status:      'complete',
      })
      .eq('id', inProgressId!);

    if (!error) {
      if (selectedPreset === 'edv' && edvLinkedHoldId) {
        await supabase
          .from('holds')
          .update({ offstandard_linked: true, cleaned_inhouse_logged_at: new Date().toISOString() })
          .eq('id', edvLinkedHoldId);
      }
      setStopTimestamp(now);
      setPendingMinutes(mins);
      setEntries(prev => [...prev, {
        id:           inProgressId!,
        startTime:    startTimestamp,
        stopTime:     now,
        minutes:      mins,
        reason:       selectedReason,
        explanation:  explanation.trim() || undefined,
        autoFromTrip: false,
        presetReason: selectedPreset,
        linkedHoldId: selectedPreset === 'edv' ? edvLinkedHoldId : null,
      }]);
      setTimerState('complete');
    }
  };

  const handleDiscard = () => {
    setTimerState('idle');
    setInProgressId(null);
    setStartTimestamp('');
    setStopTimestamp('');
    setPendingMinutes(0);
    setExplanation('');
    setSelectedPreset(null);
    setEdvLinkedHoldId(null);
    setEdvUnitNumber('');
    setEdvManagerName('');
    setEdvNoMatch(false);
    setStartError(false);
  };

  // ── Tally ─────────────────────────────────────────────────────────────────

  const offTotal         = entries.reduce((s, e) => s + e.minutes, 0);
  const activeMinutes    = Math.max(0, SHIFT_HOURS * 60 - offTotal);
  const activeHours      = activeMinutes / 60;
  const personalRate     = activeHours > 0 && carsNum > 0 ? carsNum / activeHours : 0;
  const branchBaseHours  = isPeakSeason ? 16 : 15;
  const branchOpHours    = branchBaseHours + (washbayLog?.overtimeHours ?? 0);
  const branchRate       = carsNum > 0 ? carsNum / branchOpHours : 0;
  const rate             = personalRate; // kept for rateColor + report text
  const rateColor        = !washbayLog ? 'text-gray-400 dark:text-gray-500'
    : personalRate >= STANDARD_RATE ? 'text-green-600 dark:text-green-400'
    : personalRate >= 2.5 ? 'text-amber-500'
    : 'text-red-600 dark:text-red-400';

  // ── Export ────────────────────────────────────────────────────────────────

  const handleExport = async () => {
    hapticMedium();
    const reportText = generateReportText(entries, user, carsNum);
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Off-Standard Report — ${user.name} · ${todayDateStr()}`,
          text: reportText,
        });
        return;
      } catch {
        // fall through to clipboard
      }
    }
    await navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  // ── Render ────────────────────────────────────────────────────────────────

  const INPUT = 'w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-700 text-sm text-gray-900 dark:text-gray-100 bg-white dark:bg-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition';

  return (
    <div className="space-y-5">

      {/* Timer card */}
      <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden transition-colors">
        <div className="px-4 py-3 border-b border-gray-100 dark:border-gray-800">
          <p className="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-widest">Log Off-Standard Time</p>
        </div>
        <div className="p-4 space-y-4">

          {/* Reason pills — disabled while running or complete */}
          <div>
            <p className="text-xs text-gray-400 dark:text-gray-500 mb-2">Reason</p>
            <div className="flex flex-wrap gap-2">
              {REASONS.map(r => (
                <button
                  key={r}
                  type="button"
                  disabled={timerState !== 'idle'}
                  onClick={() => { if (timerState === 'idle') { hapticLight(); setSelectedReason(r); } }}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition cursor-pointer disabled:cursor-default ${
                    selectedReason === r
                      ? 'bg-yellow-400 border-yellow-400 text-gray-900'
                      : 'border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400 hover:border-gray-300 dark:hover:border-gray-600'
                  }`}
                >
                  {r} · {OFF_STANDARD_LABELS[r].full}
                </button>
              ))}
            </div>
          </div>

          {/* Preset selector — visible when OTH selected and timer idle */}
          {selectedReason === 'OTH' && timerState === 'idle' && (
            <div>
              <p className="text-xs text-gray-400 dark:text-gray-500 mb-2">Quick reason (optional)</p>
              <div className="flex flex-wrap gap-2">
                {([
                  { value: 'fleeting_cars',  label: 'Fleeting Cars' },
                  { value: 'closing_duties', label: 'Closing Duties' },
                  { value: 'edv',            label: 'EDV' },
                ] as { value: OffStandardPresetReason; label: string }[]).map(p => (
                  <button
                    key={p.value}
                    type="button"
                    onClick={() => selectPreset(p.value)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition cursor-pointer ${
                      selectedPreset === p.value
                        ? 'bg-yellow-400 border-yellow-400 text-gray-900'
                        : 'border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400 hover:border-gray-300 dark:hover:border-gray-600'
                    }`}
                  >
                    {p.label}
                  </button>
                ))}
              </div>

              {/* EDV auto-populate result */}
              {selectedPreset === 'edv' && !edvNoMatch && edvLinkedHoldId && (
                <div className="mt-2 px-3 py-2 rounded-lg bg-teal-50 dark:bg-teal-900/20 border border-teal-200 dark:border-teal-800/40 text-xs space-y-0.5">
                  <p className="font-semibold text-teal-800 dark:text-teal-300">Hold matched</p>
                  <p className="text-teal-700 dark:text-teal-400">Unit: <span className="font-medium">{edvUnitNumber}</span></p>
                  <p className="text-teal-700 dark:text-teal-400">Released by: <span className="font-medium">{edvManagerName}</span></p>
                  <p className="text-teal-600 dark:text-teal-500 mt-1">💡 Typical EDV clean: 30–40 min</p>
                </div>
              )}

              {/* EDV no-match warning */}
              {selectedPreset === 'edv' && edvNoMatch && (
                <div className="mt-2 px-3 py-2 rounded-lg bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/40 text-xs text-amber-700 dark:text-amber-400">
                  No released detail hold found for today. Log manually or check Holds for the unit.
                </div>
              )}
            </div>
          )}

          <p className="text-xs text-blue-600 dark:text-blue-400">
            🔗 Airport trips log automatically from the Movement Log — no need to add them here.
          </p>

          {/* Start error */}
          {startError && (
            <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/40 rounded-lg px-4 py-3">
              <p className="text-xs font-semibold text-red-700 dark:text-red-400">Couldn't save — check connection and try again.</p>
            </div>
          )}

          {/* idle → Start */}
          {timerState === 'idle' && (
            <button
              type="button"
              onClick={handleStart}
              className="w-full py-3 rounded-xl bg-yellow-400 hover:bg-yellow-500 text-gray-900 text-sm font-semibold transition cursor-pointer"
            >
              Start
            </button>
          )}

          {/* running → elapsed + notes + End */}
          {timerState === 'running' && (
            <div className="space-y-3">
              <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/40 rounded-xl px-4 py-4 text-center">
                <p className="text-xs font-semibold text-amber-700 dark:text-amber-400 uppercase tracking-widest mb-1">
                  {selectedReason} · {OFF_STANDARD_LABELS[selectedReason].full}
                </p>
                <p className="text-3xl font-bold text-amber-600 dark:text-amber-400">
                  <ElapsedTicker startTime={startTimestamp} />
                </p>
                <p className="text-xs text-amber-600/70 dark:text-amber-500/70 mt-1">
                  Started {fmtTime(startTimestamp)}
                </p>
              </div>
              <div>
                <label className="text-xs text-gray-400 dark:text-gray-500 mb-1 block">Notes (optional)</label>
                <input
                  type="text"
                  value={explanation}
                  onChange={e => setExplanation(e.target.value)}
                  onBlur={e => saveNotes(e.target.value)}
                  placeholder="e.g. Waiting for dirties to arrive…"
                  className={INPUT}
                />
              </div>
              <button
                type="button"
                onClick={handleEnd}
                className="w-full py-3 rounded-xl bg-gray-900 dark:bg-gray-100 hover:bg-gray-800 dark:hover:bg-white text-white dark:text-gray-900 text-sm font-semibold transition cursor-pointer"
              >
                End
              </button>
            </div>
          )}

          {/* complete → saved card + notes still editable + Done */}
          {timerState === 'complete' && (
            <div className="space-y-3">
              <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800/40 rounded-xl px-4 py-3">
                <p className="text-xs font-semibold text-green-700 dark:text-green-400 uppercase tracking-widest mb-1">✓ Entry saved</p>
                <p className="text-sm font-medium text-green-800 dark:text-green-300">
                  {selectedReason} · {fmtTime(startTimestamp)} – {fmtTime(stopTimestamp)} · {fmtMinutes(pendingMinutes)}
                </p>
              </div>
              <div>
                <label className="text-xs text-gray-400 dark:text-gray-500 mb-1 block">Notes (optional)</label>
                <input
                  type="text"
                  value={explanation}
                  onChange={e => setExplanation(e.target.value)}
                  onBlur={e => saveNotes(e.target.value)}
                  placeholder="e.g. Waiting for dirties to arrive…"
                  className={INPUT}
                  autoFocus
                />
              </div>
              <button
                type="button"
                onClick={handleDiscard}
                className="w-full py-3 rounded-xl bg-yellow-400 hover:bg-yellow-500 text-gray-900 text-sm font-semibold transition cursor-pointer"
              >
                Done
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Entry list */}
      {entries.length > 0 && (
        <div className="space-y-2">
          <p className="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-widest">Entries</p>
          {entries.map(entry => (
            <div
              key={entry.id}
              className={`rounded-xl border px-4 py-3 transition-colors ${
                entry.autoFromTrip
                  ? 'bg-blue-50 dark:bg-blue-900/10 border-blue-200 dark:border-blue-800/40'
                  : 'bg-white dark:bg-gray-900 border-gray-200 dark:border-gray-800'
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-xs font-semibold text-gray-900 dark:text-gray-100">
                      {fmtTime(entry.startTime)} – {fmtTime(entry.stopTime)}
                    </span>
                    <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400">
                      {entry.reason}
                    </span>
                    <span className="text-xs text-gray-500 dark:text-gray-400">
                      {fmtMinutes(entry.minutes)}
                    </span>
                    {entry.autoFromTrip && (
                      <span className="text-[10px] text-blue-600 dark:text-blue-400 font-medium">🔗 From movement log</span>
                    )}
                  </div>
                  {entry.explanation && (
                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">{entry.explanation}</p>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Shift summary + export */}
      <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden transition-colors">
        <div className="px-4 py-3 border-b border-gray-100 dark:border-gray-800">
          <p className="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-widest">Shift Summary</p>
        </div>
        <div className="p-4 space-y-4">
          <div className="space-y-2 text-sm">
            <div className="flex justify-between text-gray-600 dark:text-gray-400">
              <span>Shift hours</span>
              <span className="font-medium text-gray-900 dark:text-gray-100">{SHIFT_HOURS}h</span>
            </div>
            <div className="flex justify-between text-gray-600 dark:text-gray-400">
              <span>Off-standard total</span>
              <span className="font-medium text-gray-900 dark:text-gray-100">{fmtMinutes(offTotal)}</span>
            </div>
            <div className="flex justify-between text-gray-600 dark:text-gray-400 pt-1 border-t border-gray-100 dark:border-gray-800">
              <span>Active cleaning</span>
              <span className="font-semibold text-gray-900 dark:text-gray-100">{fmtMinutes(activeMinutes)}</span>
            </div>
          </div>

          <div className="flex justify-between text-sm text-gray-600 dark:text-gray-400">
            <span>Cars cleaned (team)</span>
            {washbayLog ? (
              <span className="font-semibold text-gray-900 dark:text-gray-100">{carsNum}</span>
            ) : (
              <span className="text-xs text-gray-400 dark:text-gray-500 italic">Submit closing duties to see</span>
            )}
          </div>

          {washbayLog && (
            <div className={`rounded-lg px-4 py-3 border ${
              rate >= STANDARD_RATE
                ? 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800/50'
                : rate >= 2.5
                ? 'bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800/50'
                : 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800/50'
            }`}>
              <div className="flex justify-between items-baseline">
                <span className="text-xs text-gray-500 dark:text-gray-400">Standard rate</span>
                <span className="text-sm font-medium text-gray-600 dark:text-gray-400">{STANDARD_RATE.toFixed(1)} / hr</span>
              </div>
              <div className="flex justify-between items-baseline mt-1">
                <span className="text-xs text-gray-500 dark:text-gray-400">Personal rate</span>
                <span className={`text-lg font-bold ${rateColor}`}>{personalRate.toFixed(1)} / hr</span>
              </div>
              <div className="flex justify-between items-baseline mt-1 pt-1 border-t border-gray-100 dark:border-gray-800">
                <span className="text-xs text-gray-500 dark:text-gray-400">Branch rate ({branchOpHours}h window)</span>
                <span className="text-sm font-semibold text-gray-700 dark:text-gray-300">{branchRate.toFixed(1)} / hr</span>
              </div>
            </div>
          )}

          <button
            type="button"
            onClick={handleExport}
            className="w-full py-3 rounded-xl bg-gray-900 dark:bg-gray-100 hover:bg-gray-800 dark:hover:bg-white text-white dark:text-gray-900 text-sm font-semibold transition cursor-pointer"
          >
            {copied ? '✓ Copied to clipboard' : 'Export Shift Report'}
          </button>
        </div>
      </div>

    </div>
  );
}
